-- Ranisa-specific catalogue and media. Existing enquiry and Nile tables are untouched.
create table if not exists public.ranisa_admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  granted_at timestamptz not null default now()
);
alter table public.ranisa_admin_users enable row level security;
grant select on public.ranisa_admin_users to authenticated;
revoke insert, update, delete on public.ranisa_admin_users from anon, authenticated;
create policy "Ranisa admins can identify their own membership"
on public.ranisa_admin_users for select to authenticated
using (user_id = (select auth.uid()));

create table if not exists public.ranisa_products (
  id integer generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 140),
  category text not null check (char_length(category) between 2 and 80),
  description text not null default '' check (char_length(description) <= 3000),
  price numeric(10,2) check (price >= 0),
  image_url text not null default '',
  gallery_images text[] not null default '{}',
  badge text not null default '' check (char_length(badge) <= 32),
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.ranisa_products enable row level security;
grant select on public.ranisa_products to anon, authenticated;
grant insert, update, delete on public.ranisa_products to authenticated;
grant usage, select on sequence public.ranisa_products_id_seq to authenticated;
create policy "Visitors see visible Ranisa products" on public.ranisa_products
  for select to anon using (is_active);
create policy "Admins see all Ranisa products" on public.ranisa_products
  for select to authenticated using (
    is_active or exists (select 1 from public.ranisa_admin_users
      where user_id = (select auth.uid()))
  );
create policy "Admins add Ranisa products" on public.ranisa_products
  for insert to authenticated with check (
    exists (select 1 from public.ranisa_admin_users
      where user_id = (select auth.uid()))
  );
create policy "Admins edit Ranisa products" on public.ranisa_products
  for update to authenticated
  using (exists (select 1 from public.ranisa_admin_users where user_id = (select auth.uid())))
  with check (exists (select 1 from public.ranisa_admin_users where user_id = (select auth.uid())));
create policy "Admins delete Ranisa products" on public.ranisa_products
  for delete to authenticated
  using (exists (select 1 from public.ranisa_admin_users where user_id = (select auth.uid())));

create table if not exists public.ranisa_site_media (
  slot text primary key check (slot in ('hero','about','story','editorial_1','editorial_2','editorial_3','logo')),
  image_url text not null default '',
  alt_text text not null default '' check (char_length(alt_text) <= 250),
  updated_at timestamptz not null default now()
);
alter table public.ranisa_site_media enable row level security;
grant select on public.ranisa_site_media to anon, authenticated;
grant update on public.ranisa_site_media to authenticated;
create policy "Visitors see Ranisa site photos" on public.ranisa_site_media
  for select to anon using (true);
create policy "Signed-in visitors see Ranisa site photos" on public.ranisa_site_media
  for select to authenticated using (true);
create policy "Admins edit Ranisa site photos" on public.ranisa_site_media
  for update to authenticated
  using (exists (select 1 from public.ranisa_admin_users where user_id = (select auth.uid())))
  with check (exists (select 1 from public.ranisa_admin_users where user_id = (select auth.uid())));

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('ranisa-products','ranisa-products',true,10485760,
        array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set
  public = true, file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
create policy "Ranisa admins upload catalogue images" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'ranisa-products'
    and exists (select 1 from public.ranisa_admin_users where user_id = (select auth.uid())));
create policy "Ranisa admins list catalogue images" on storage.objects
  for select to authenticated
  using (bucket_id = 'ranisa-products'
    and exists (select 1 from public.ranisa_admin_users where user_id = (select auth.uid())));
create policy "Ranisa admins delete catalogue images" on storage.objects
  for delete to authenticated
  using (bucket_id = 'ranisa-products'
    and exists (select 1 from public.ranisa_admin_users where user_id = (select auth.uid())));

insert into public.ranisa_site_media(slot,image_url,alt_text)
values
  ('hero','/assets/ranisa-throne-hero.jpeg','Woman seated in an ornate royal setting'),
  ('about','/assets/ranisa-about.png','Ranisa Boutique about us artwork'),
  ('story','/assets/4-2-1024x1024.jpg','Women’s boutique style inspiration'),
  ('editorial_1','/assets/editorial-queen.png','Woman placing a jeweled crown on her head'),
  ('editorial_2','/assets/editorial-pop-sari.png','Woman in a red sari and sunglasses'),
  ('editorial_3','/assets/editorial-pop-portrait.png','Colourful portrait of a woman'),
  ('logo','/assets/ranisa-r-logo.png','Ranisa Boutique crowned R logo')
on conflict (slot) do nothing;
