"use client";
import {useRef,useState} from "react";
import Link from "next/link";
import dynamic from "next/dynamic";
import {motion,AnimatePresence,useScroll,useTransform,useReducedMotion,useInView} from "motion/react";
import EditorialImage from "./editorial-image";
import Reveal from "./reveal";
const SignatureScene=dynamic(()=>import("./signature-scene"));
export function LazySignature(){const ref=useRef<HTMLDivElement>(null),visible=useInView(ref,{once:true,margin:"500px"});return <div ref={ref} className="signature-reserve">{visible?<SignatureScene/>:<div className="signature-placeholder"><p className="eyebrow">THE SIGNATURE EDIT</p><h2>Designed to be remembered.</h2></div>}</div>}
const chapters=[{number:"01",title:"Rooted in tradition.",body:"The richness of Indian wear is in its details. A considered silhouette. A beautiful drape. An embroidery that catches the light. We bring these elements together with an eye for the way you want to feel."},{number:"02",title:"Made personal.",body:"Every celebration has its own story. Tell us yours, and we’ll help you explore fabrics, colours and finishing touches. From a graceful suit to a festive lehenga, the most important detail is you."},{number:"03",title:"A conversation, first.",body:"Visit our boutique in Dehradun or begin with a message. We’ll talk through your inspiration, fit and occasion, then agree on the details of a piece made especially for you."}];
export function BrandStory(){return <section className="brand-story section-shell" id="our-story"><div className="story-picture"><EditorialImage asset="founder" alt="A personal moment in a pink sari at Ranisa Boutique"/><span className="image-caption">FROM DEHRADUN, WITH LOVE.</span></div><div className="story-chapters"><p className="eyebrow">THE HEART OF RANISA</p><h2>Some things are<br/><i>always personal.</i></h2>{chapters.map(c=><Reveal key={c.number}><article className="story-chapter"><span>{c.number}</span><h3>{c.title}</h3><p>{c.body}</p></article></Reveal>)}<Link className="text-link" href="/about">Discover our story <span aria-hidden="true">↗</span></Link></div></section>}
const steps=[['Share Your Inspiration','A photograph, a colour, a feeling. Tell us what you have in mind.'],['Choose Your Style','Together, we discuss the silhouette, fabric, fit and finishing details.'],['Crafted by Ranisa','Your design takes shape once the measurements, price and timing are agreed.'],['Delivered to You','We confirm collection or delivery arrangements when your piece is ready.']];
export function CustomJourney(){const ref=useRef<HTMLElement>(null),reduce=useReducedMotion();const {scrollYProgress}=useScroll({target:ref,offset:["start 90%","end 70%"]});const silkY=useTransform(scrollYProgress,[0,1],[25,-25]);return <section className="custom-journey" ref={ref}><motion.img src="/media/silk.webp" alt="" aria-hidden="true" className="journey-silk" width="1024" height="1536" loading="lazy" style={{y:reduce?0:silkY}}/><div className="section-shell journey-inner"><Reveal><p className="eyebrow">YOUR IMAGINATION. OUR CRAFT.</p><h2>Made Especially<br/><i>for You.</i></h2><p className="section-intro">A thoughtful journey from your first idea to a piece that feels entirely your own.</p></Reveal><div className="journey-steps"><motion.div aria-hidden="true" className="gold-thread" style={{scaleX:reduce?1:scrollYProgress}}/>{steps.map(([title,body],i)=><Reveal key={title} delay={i*.07}><article><span className="step-number">0{i+1}</span><h3>{title}</h3><p>{body}</p></article></Reveal>)}</div><Link className="button" href="/custom">Begin your custom design <span aria-hidden="true">↗</span></Link></div></section>}
const notes=[{quote:"The most beautiful thing you can wear is something that feels like you.",caption:"PERSONAL STYLE"},{quote:"A celebration lasts a day. The way you felt can stay with you forever.",caption:"MOMENTS THAT MATTER"},{quote:"Thoughtful details turn a beautiful outfit into your favourite one.",caption:"THE LITTLE THINGS"}];
export function AtelierNotes(){const [index,setIndex]=useState(0),reduce=useReducedMotion();return <section className="atelier-notes section-shell" aria-label="Ranisa design philosophy"><div><p className="eyebrow">NOTES FROM THE ATELIER</p><span className="large-quote" aria-hidden="true">“</span></div><div className="quote-content" data-cursor="↔"><AnimatePresence mode="wait"><motion.blockquote key={index} initial={reduce?false:{opacity:0,x:15,filter:"blur(4px)"}} animate={{opacity:1,x:0,filter:"blur(0px)"}} exit={{opacity:0,x:-15}} transition={{duration:.4}}><p>{notes[index].quote}</p><footer>THE RANISA PHILOSOPHY <span>— {notes[index].caption}</span></footer></motion.blockquote></AnimatePresence><div className="carousel-controls"><span>0{index+1} / 03</span><button className="icon-button" aria-label="Previous atelier note" onClick={()=>setIndex((index+2)%3)}>←</button><button className="icon-button" aria-label="Next atelier note" onClick={()=>setIndex((index+1)%3)}>→</button></div></div></section>}
const faqs=[['Can I customise an outfit?','Yes. Share your inspiration for a suit, lehenga or dress material. We’ll discuss design, measurements, price and timing with you on WhatsApp before your order begins.'],['Which payment options are available?','UPI and cash on delivery are available. Payment details and any delivery charges are confirmed with you on WhatsApp.'],['Can I return or exchange an order?','All purchases are final. We do not accept returns, refunds or exchanges. Please confirm every detail with us before ordering.'],['How do I send reference images?','Choose your images in the custom-order form. The form prepares your details for WhatsApp, where you can attach those same photos and continue the conversation.']];
export function BoutiqueFAQ(){const [open,setOpen]=useState<number|null>(null),reduce=useReducedMotion();return <section className="faq-editorial section-shell"><div><p className="eyebrow">A FEW THINGS TO KNOW</p><h2>A little<br/><i>clarity.</i></h2><Link className="text-link" href="/contact">Talk to us <span aria-hidden="true">↗</span></Link></div><div>{faqs.map(([q,a],i)=><div className="faq-item" key={q}><h3><button aria-expanded={open===i} aria-controls={`faq-${i}`} onClick={()=>setOpen(open===i?null:i)}>{q}<span aria-hidden="true">{open===i?'−':'+'}</span></button></h3><AnimatePresence>{open===i&&<motion.div id={`faq-${i}`} initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} transition={{duration:reduce?0:.3}}><p>{a}</p></motion.div>}</AnimatePresence></div>)}</div></section>}
