"use client";
import {useEffect,useRef} from "react";
import {useReducedMotion} from "motion/react";
export default function ScrollCanvasScene(){
 const ref=useRef<HTMLCanvasElement>(null),reduce=useReducedMotion();
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;const ctx=canvas.getContext("2d");if(!ctx)return;const model=new Image(),silk=new Image();model.src="/media/signature.webp";silk.src="/media/silk.webp";let raf=0,progress=0,ready=false;
 const particles=Array.from({length:70},(_,i)=>({x:(i*83)%1000,y:(i*47)%700,s:1+(i%4),v:.12+(i%5)/14,a:.15+(i%5)/16}));
 const resize=()=>{const d=Math.min(window.devicePixelRatio||1,2),r=canvas.getBoundingClientRect();canvas.width=Math.max(1,Math.floor(r.width*d));canvas.height=Math.max(1,Math.floor(r.height*d));ctx.setTransform(d,0,0,d,0,0)};
 const draw=()=>{const r=canvas.getBoundingClientRect(),w=r.width,h=r.height;ctx.clearRect(0,0,w,h);const grad=ctx.createRadialGradient(w*.52,h*.55,0,w*.52,h*.55,Math.max(w,h)*.75);grad.addColorStop(0,"#713649");grad.addColorStop(.48,"#351d27");grad.addColorStop(1,"#1b1217");ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);ctx.save();ctx.globalAlpha=.25;for(let i=0;i<particles.length;i++){const p=particles[i],x=(p.x/1000*w+progress*p.v*130)%w,y=(p.y/700*h+progress*p.v*100)%h;ctx.fillStyle=i%3?"#d9bd87":"#f4e8d0";ctx.globalAlpha=p.a;ctx.beginPath();ctx.arc(x,y,p.s,0,Math.PI*2);ctx.fill()}ctx.restore();if(model.complete&&model.naturalWidth){ctx.save();const maxH=h*.76*(1+progress*.08),ratio=model.naturalWidth/model.naturalHeight,mh=maxH,mw=mh*ratio;ctx.translate(w*.54,h*.53);ctx.rotate((progress-.5)*.16);ctx.globalAlpha=.94;ctx.shadowColor="rgba(5,0,4,.55)";ctx.shadowBlur=34;ctx.drawImage(model,-mw/2,-mh/2,mw,mh);ctx.restore()}if(silk.complete&&silk.naturalWidth){ctx.save();const sh=h*.8,s=sh/silk.naturalHeight,sw=silk.naturalWidth*s;ctx.globalAlpha=.22;ctx.translate(w*.78,h*.54);ctx.rotate(-.45+progress*.22);ctx.drawImage(silk,-sw/2,-sh/2,sw,sh);ctx.restore()}if(!reduce){raf=requestAnimationFrame(draw)}};
 const update=()=>{const r=canvas.getBoundingClientRect(),vh=window.innerHeight;progress=Math.max(0,Math.min(1,(vh-r.top)/(vh+r.height)));if(reduce)draw()};const onScroll=()=>{update();if(reduce)return;if(!raf)raf=requestAnimationFrame(draw)};const onResize=()=>{resize();draw()};resize();model.onload=()=>{ready=true;draw()};silk.onload=()=>draw();update();draw();window.addEventListener("scroll",onScroll,{passive:true});window.addEventListener("resize",onResize);return()=>{cancelAnimationFrame(raf);window.removeEventListener("scroll",onScroll);window.removeEventListener("resize",onResize)}} , [reduce]);
 return <canvas ref={ref} className="scroll-canvas-scene" aria-hidden="true"/>;
}
