"use client";
import {updateCart} from "../components/cart-store";
import EditorialImage from "../components/editorial-image";
import Reveal from "../components/reveal";
import { useEffect, useMemo, useState } from "react";
type Product={id:string;name:string;category:string;fabric:string;price:number;imageUrl:string;description:string};
export default function Shop(){
 const [products,setProducts]=useState<Product[]>([]),[category,setCategory]=useState("all"),[fabric,setFabric]=useState("all"),[max,setMax]=useState(""),[sort,setSort]=useState("featured"),[loading,setLoading]=useState(true),[added,setAdded]=useState(""),[error,setError]=useState("");
 useEffect(()=>{const type=new URLSearchParams(window.location.search).get("type");if(type&&["suit","lehenga","material"].includes(type))setCategory(type);fetch("/api/products").then(r=>{if(!r.ok)throw Error("Could not load collection");return r.json() as Promise<{products?:Product[]}>}).then(d=>setProducts(d.products||[])).catch(()=>setError("We couldn’t load the collection. Please refresh, or contact us on WhatsApp.")).finally(()=>setLoading(false))},[]);
 const fabrics=Array.from(new Set(products.map(p=>p.fabric).filter(Boolean)));
 const visible=useMemo(()=>{let a=products.filter(p=>(category==="all"||p.category===category)&&(fabric==="all"||p.fabric===fabric)&&(!max||p.price<=Number(max)));if(sort==="low")a.sort((x,y)=>x.price-y.price);if(sort==="high")a.sort((x,y)=>y.price-x.price);return a},[products,category,fabric,max,sort]);
 const type=(s:string)=>s==="material"?"Dress material":s[0].toUpperCase()+s.slice(1);
 function addToBag(id:string){updateCart(id,1);setAdded(id);setTimeout(()=>setAdded(""),1600)}
 return <main className="page"><Reveal><p className="kicker">THE RANISA COLLECTION</p><h1>The Ranisa<br/><i>Collection.</i></h1><p>Traditional suits, lehengas and dress materials, customised on order.</p>
 <section className="lookbook-intro"><EditorialImage asset="suits" alt="Campaign inspiration: a blush embroidered suit"/><div><p className="eyebrow">THE ART OF THE SUIT</p><h2>A softer kind<br/><i>of statement.</i></h2><p>Beautiful fabrics. Thoughtful details. A silhouette that feels like you.</p><a className="text-link" href="/custom">Create your own look</a><p className="editorial-disclaimer">Campaign inspiration. Available pieces are shown below.</p></div></section><section className="filters" aria-label="Filter products"><label>Clothing type<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All types</option><option value="suit">Suit</option><option value="lehenga">Lehenga</option><option value="material">Dress material</option></select></label><label>Fabric<select value={fabric} onChange={e=>setFabric(e.target.value)}><option value="all">All fabrics</option>{fabrics.map(x=><option key={x}>{x}</option>)}</select></label><label>Maximum price (₹)<input aria-label="Maximum price in rupees" inputMode="numeric" placeholder="Any price" value={max} onChange={e=>setMax(e.target.value.replace(/[^0-9]/g,""))}/></label><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></label></section>
 {error?<div className="empty" role="alert"><h2>Let’s try again.</h2><p>{error}</p><a className="button" href="https://wa.me/919004517938">Talk to Ranisa</a></div>:loading?<div className="empty">Loading collection…</div>:visible.length?<div className="shop-grid">{visible.map(p=><article className="shop-card" key={p.id}><div className="shop-photo">{p.imageUrl?<img src={p.imageUrl} alt={p.name} loading="lazy" decoding="async" fetchPriority="low"/>:<div className="empty">Image coming soon</div>}</div><div className="shop-card-info"><small>{type(p.category)}{p.fabric?` · ${p.fabric}`:""}</small><h3>{p.name}</h3><b>₹{p.price.toLocaleString("en-IN")}</b>{p.description&&<p>{p.description}</p>}<button className="btn" onClick={()=>addToBag(p.id)}>{added===p.id?"ADDED TO BAG":"ADD TO BAG"}</button> <a href={`https://wa.me/919004517938?text=${encodeURIComponent(`Hello Ranisa Boutique, I am interested in ${p.name} (₹${p.price}). Please share details.`)}`} target="_blank" rel="noreferrer">Enquire</a></div></article>)}</div>:<div className="empty"><h2>Let’s find your next favourite.</h2><p>Our online edit is being prepared. In the meantime, discover fabrics and designs with us in a personal conversation.</p><a className="btn" href="https://wa.me/919004517938">ENQUIRE ON WHATSAPP</a></div>}</Reveal></main>
}
